name: unison-codebase-sqlite
github: unisonweb/unison

library:
  source-dirs: .

extra-source-files:
  - sql/*

dependencies:
  - Only
  - base
  - bytes
  - bytestring
  - containers
  - extra
  - here
  - lens
  - monad-validate
  - mtl
  - safe
  - text
  - transformers
  - unison-codebase
  - unison-codebase-sync
  - unison-core
  - unison-prelude
  - unison-sqlite
  - unison-util
  - unison-util-serialization
  - unison-util-term
  - unliftio
  - vector

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - DoAndIfThenElse
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - ViewPatterns
