# https://docs.haskellstack.org/en/stable/travis_ci/
jobs:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11.6
    - os: osx
      osx_image: xcode11.3

language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/parser-typechecker/.stack-work
  - $TRAVIS_BUILD_DIR/yaks/easytest/.stack-work
  - $TRAVIS_BUILD_DIR/unison-core/.stack-work
  - $TRAVIS_BUILD_DIR/.stack-work

before_cache:
# Do any cleanup here to avoid caching junk.

before_install:
- find $HOME/.stack -type f | xargs sha1sum
- find $TRAVIS_BUILD_DIR/parser-typechecker/.stack-work -type f | xargs sha1sum
- find $TRAVIS_BUILD_DIR/yaks/easytest/.stack-work -type f | xargs sha1sum
- find $TRAVIS_BUILD_DIR/unison-core/.stack-work -type f | xargs sha1sum
- find $TRAVIS_BUILD_DIR/.stack-work -type f | xargs sha1sum
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -sSL https://get.haskellstack.org/ | sh

install:
- stack ghc -- --version
- stack --no-terminal build
- stack --no-terminal exec tests
- stack --no-terminal exec transcripts
# fail if running transcripts modified any versioned files
- git diff
- x=`git status --porcelain -uno` bash -c 'if [[ -n $x ]]; then echo "$x" && false; fi'
- find $HOME/.stack -type f | xargs sha1sum
- find $TRAVIS_BUILD_DIR/parser-typechecker/.stack-work -type f | xargs sha1sum
- find $TRAVIS_BUILD_DIR/yaks/easytest/.stack-work -type f | xargs sha1sum
- find $TRAVIS_BUILD_DIR/unison-core/.stack-work -type f | xargs sha1sum
- find $TRAVIS_BUILD_DIR/.stack-work -type f | xargs sha1sum
