name: unison-core
github: unisonweb/unison

library:
  source-dirs: .
  when:
    - condition: false
      other-modules: Paths_unison_core

dependencies:
  - base
  - containers
  - vector
  - unison-util
