name: unison-codebase-sync
github: unisonweb/unison

library:
  source-dirs: .

dependencies:
  - base
  - bytes
  - bytestring
  - containers
  - extra
  - here
  - lens
  - monad-validate
  - mtl
  - sqlite-simple
  - text
  - transformers
  - unison-codebase
  - unison-core
  - unison-util
  - unison-util-serialization
  - unison-util-term
  - unliftio
  - vector