name: "create-release"

on:
  push:
    tags:
      - "release/*"

jobs:
  release:
    name: "create-release"
    runs-on: "ubuntu-latest"

    strategy:
      # Run each build to completion, regardless of if any have failed
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2



      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          draft: true

