name: CI

defaults:
  run:
    working-directory: unison

on:
  push:
    branches:
      - trunk
      # TODO: remove
      - haddock-upload

jobs:
  build:
    name: Haddocks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: unison

      # The number towards the beginning of the cache keys allow you to manually avoid using a previous cache.
      # GitHub will automatically delete caches that haven't been accessed in 7 days, but there is no way to
      # purge one manually.

      # Cache ~/.stack, keyed by the contents of 'stack.yaml'.
      - uses: actions/cache@v2
        name: cache ~/.stack
        with:
          path: ~/.stack
          key: stack-0_Linux-${{hashFiles('stack.yaml')}}
          # Fall-back to use the most recent cache for the OS from any stack.yaml
          restore-keys: stack-0_Linux

      # Cache each local package's ~/.stack-work for fast incremental builds in CI.
      - uses: actions/cache@v2
        name: cache .stack-work
        with:
          path: |
            **/.stack-work
          # Use separate caches for each OS.
          # Caches from this branch will be used first, then trunk caches will
          # be used as a backup.
          key: stack-work-2_Linux-haddocks
          # Fall-back to use the most recent cache for the OS
          restore-keys: stack-work-2_Linux

      # Install stack by downloading the binary from GitHub. The installation process is different for Linux and macOS,
      # so this is split into two steps, only one of which will run on any particular build.
      - name: install stack
        working-directory: unison
        run: |
          curl -L https://github.com/commercialhaskell/stack/releases/download/v2.5.1/stack-2.5.1-linux-x86_64.tar.gz | tar -xz
          echo "$HOME/stack-2.5.1-linux-x86_64/" >> $GITHUB_PATH

      # One of the transcripts fails if the user's git name hasn't been set.
      - name: set git user info
        working-directory: unison
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: build with haddocks
        working-directory: unison
        run: stack --no-terminal build --fast --haddock

      # Haddocks
      - name: Checkout haddocks branch
        uses: actions/checkout@v2
        with:
          ref: 'haddocks'
          path: 'haddocks'

      - name: Copy haddocks
        working-directory: 'unison'
        run: |
          docs_root="$(stack path --local-doc-root)"
          # Erase any stale files
          cd "$GITHUB_WORKSPACE"/haddocks
          rm -rf ./*
          cp -r "${docs_root}"/* "$GITHUB_WORKSPACE"/haddocks
          git add .
          git commit -m "Regenerate haddocks based on ${GITHUB_SHA}"
          git push
