name: Haddocks

# Only run on new pushes to trunk
on:
  push:
    branches:
      - trunk

jobs:
  build:
    name: "build_haddocks"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      # The random number towards the beginning of the cache keys below are meant to be bumped as a crude means to clear
      # a cache. GitHub will automatically delete caches that haven't been accessed in 7 days, but there is no way to
      # purge one manually.

      # Cache ~/.stack, keyed by the contents of 'stack.yaml'.
      - uses: actions/cache@v2
        name: cache ~/.stack
        with:
          path: ~/.stack
          key: stack-0_ubuntu-20.04-${{hashFiles('stack.yaml')}}

      # Cache each local package's ~/.stack-work for fast incremental builds in CI.
      - uses: actions/cache@v2
        name: cache .stack-work
        with:
          path: |
            .stack-work
            parser-typechecker/.stack-work
            unison-core/.stack-work
            yaks/easytest/.stack-work
            # Main cache key: commit hash. This should always result in a cache miss...
          key: stack-work-2_ubuntu-20.04-${{github.sha}}
          # ...but then fall back on the latest cache stored (on this branch)
          restore-keys: stack-work-2_ubuntu-20.04-${{github.ref}}

      # Install stack by downloading the binary from GitHub. The installation process is different for Linux and macOS,
      # so this is split into two steps, only one of which will run on any particular build.
      - name: install stack 
        run: |
          curl -L https://github.com/commercialhaskell/stack/releases/download/v2.5.1/stack-2.5.1-linux-x86_64.tar.gz | tar -xz
          echo "$HOME/stack-2.5.1-linux-x86_64/" >> $GITHUB_PATH

      # One of the transcripts fails if the user's git name hasn't been set.
      - name: set git user info
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: build-haddocks
        run: ./scripts/haddocks.sh
